
DROP TABLE STUDENT;
DROP TABLE COURSE;
DROP TABLE INSTRUCTOR;

CREATE COLUMN TABLE STUDENT
(
	ID INT,
	NAME NVARCHAR(10),
	COURSE NVARCHAR(10)
);

INSERT INTO STUDENT VALUES (1, 'John', 'C1');
INSERT INTO STUDENT VALUES (1, 'John', 'C5');
INSERT INTO STUDENT VALUES (2, 'David', 'C4');
INSERT INTO STUDENT VALUES (3, 'Steven', 'C6');
INSERT INTO STUDENT VALUES (4, 'Alex', 'C7');
INSERT INTO STUDENT VALUES(4, 'Alex', 'C2');
INSERT INTO STUDENT VALUES (5, 'Om', 'C4');
INSERT INTO STUDENT VALUES (6, 'Ram', 'C5');
INSERT INTO STUDENT VALUES (9, 'Zia', NULL);

CREATE COLUMN TABLE COURSE
(
	ID NVARCHAR(3),
	NAME NVARCHAR(10),
	PRICE INT,
	INSTRUCTOR INT
);

INSERT INTO COURSE VALUES ('C1', 'SQL', 500, 2);
INSERT INTO COURSE VALUES ('C2', 'CSS', 200, 4);
INSERT INTO COURSE VALUES ('C3', 'Python', 300, 2);
INSERT INTO COURSE VALUES ('C4', 'SAP', 400, 4);
INSERT INTO COURSE VALUES ('C5', 'HANA', 500, 7);
INSERT INTO COURSE VALUES ('C6', 'HTML', 100, 9);
INSERT INTO COURSE VALUES ('C7', 'JAVA', 250, 10);

CREATE COLUMN TABLE INSTRUCTOR
(
	ID INT,
	NAME NVARCHAR(10)
);

INSERT INTO INSTRUCTOR VALUES (2, 'David');
INSERT INTO INSTRUCTOR VALUES (4, 'Alex');
INSERT INTO INSTRUCTOR VALUES (7, 'Sachin');
INSERT INTO INSTRUCTOR VALUES (8, 'Jane');
INSERT INTO INSTRUCTOR VALUES (9, 'Zia');

SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM INSTRUCTOR;
