SELECT 
	SAGBOOKDAYS.AGENCYNUM,
	STOPAGENCY.NAME,
	SAGBOOKDAYS.ORDERDAY,
	SAGBOOKDAYS.DAYCOUNT
FROM 
	SAGBOOKDAYS
	INNER JOIN
	STOPAGENCY
	ON SAGBOOKDAYS.AGENCYNUM = STOPAGENCY.AGENCYNUM
WHERE (SAGBOOKDAYS.DAYCOUNT IN (SELECT max(DAYCOUNT)
FROM SAGBOOKDAYS
GROUP BY AGENCYNUM));