
 DATA: E_S_RESULT TYPE _ty_s_TG_1 .
 DATA: E_T_RESULT TYPE _ty_t_TG_1 

 LOOP AT RESULT_PACKAGE INTO E_S_RESULT. 
 
 APPEND E_S_RESULT TO E_T_RESULT.
    ENDLOOP.
 
    REFRESH RESULT_PACKAGE.
    MOVE E_T_RESULT[] TO RESULT_PACKAGE[]. 


 		 
 		 
