outTab =
SELECT
    (itab_cust.CUST_GRP4) as ZDOEKUNDE_CUST_GRP4,
    RECORD,
    SQL__PROCEDURE__SOURCE__RECORD
FROM
    :inTab as intab
    LEFT OUTER JOIN "/BI0/PCUSTOMER" as itab_cust on intab."/BIC/DOEBKUNDE" = itab_cust.CUSTOMER;

errorTab =
SELECT
    '' AS ERROR_TEXT,
    '' AS SQL__PROCEDURE__SOURCE__RECORD
FROM
    PUBLIC.DUMMY
WHERE
    DUMMY <> 'X';