SELECT
    DISTINCT t1."PD_001_POSITION",
    t1."PD_001_ACCOUNT" as acc1,
    t1."PD_001_TR_CURRENCY"
FROM
    "EXP_HR_PCP_TRANSACTION_ACT" AS t1
    JOIN (
        SELECT
            "PD_001_POSITION",
            "PD_001_TR_CURRENCY"
        FROM
            "EXP_HR_PCP_TRANSACTION_ACT"
        WHERE
            "PD_001_ACCOUNT" = 'KN_004_BONUS'
    ) AS t2 ON t1."PD_001_POSITION" = t2."PD_001_POSITION"
WHERE
    t1."PD_001_ACCOUNT" = 'KN_014_SALARY'
    AND t1."PD_001_TR_CURRENCY" != t2."PD_001_TR_CURRENCY"